version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: resume_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ResumeDB
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit_container
    depends_on:
      - mysql
    ports:
      - "8501:8501"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: "user"
      DB_PASSWORD: "userpassword"
      DB_NAME:  "ResumeDB"
volumes:
  mysql_data: